name: Workiom
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router:
  sizer: ^3.1.3
  dio:
  flutter_secure_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
